version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_USER=root
      #- MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeemanager
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306

  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - "8080:8080"

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone